<<<<<<< HEAD
// Schema for reference for Firebase Database

/**
 * One folder for users, uniquely identified by their uids
 *
 * challenges contains a list of Strings, where each string is a challengeUID to
 * be able to query the challenges folder
 */
User: {
  uid: String,
  name: String,
  email: String,
  balance: Integer,
  challenges: [String]
}

/**
 * One folder for challenges, uniquely identified by their uid generated by Firebase
 *
 * participants is a list of Strings, where each string is the uid of the user
 *
 * checkInDeadline is a String in format HH:MM in military time
 * TODO: likely make challenges daily at the same time to keep simple for now
 *
 * checkIns contains checkIn objects where the keys are Strings of dates
 * in the format YYYY-MM-DD.
 * Inside each checkIn, there are keys for each of the participants to access
 * their check-in time (also HH:MM in military time), description, photo, and
 * location for that particular day
 */
 Challenge: {
   uid: String, 
   participants: [String],
   participantNames: [String],
   title: String,
   description: String,
   cost: Integer,
   checkInDeadline: String,
   checkIns: {
     checkIn1: {
       particpant1Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpant2Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpantNEmail: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
     },
     checkIn2: {
       particpant1Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpant2Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpantNEmail: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
     },
     checkIn3: {

     }
   }
 }
=======
// Schema for reference for Firebase Database

/**
 * One folder for users, uniquely identified by their uids
 *
 * challenges contains a list of Strings, where each string is a challengeUID to
 * be able to query the challenges folder
 */
User: {
  uid: String,
  name: String,
  email: String,
  balance: Integer,
  challenges: [String]
}

/**
 * One folder for challenges, uniquely identified by their uid generated by Firebase
 *
 * participants is a list of Strings, where each string is the uid of the user
 *
 * checkInDeadline is a String in format HH:MM in military time
 * TODO: likely make challenges daily at the same time to keep simple for now
 *
 * checkIns contains checkIn objects where the keys are Strings of dates
 * in the format YYYY-MM-DD.
 * Inside each checkIn, there are keys for each of the participants to access
 * their check-in time (also HH:MM in military time), description, photo, and
 * location for that particular day
 */
 Challenge: {
   uid: String, 
   participants: [String],
   participantNames: [String],
   title: String,
   description: String,
   cost: Integer,
   checkInDeadline: String,
   checkIns: {
     checkIn1: {
       particpant1Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpant2Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpantNEmail: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
     },
     checkIn2: {
       particpant1Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpant2Email: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
       particpantNEmail: {
         participantName: String,
         checkInTime: String,
         description: String,
         photoURL: String,
         location: String
       },
     },
     checkIn3: {

     }
   }
 }
>>>>>>> ea41975d654404a46265eb92acdad176156ff3ef
