// Schema for reference for Firebase Database

/**
 * One folder for users, uniquely identified by their emails, most likely
 *
 * challenges contains a list of Strings, where each string is a challengeUID to
 * be able to query the challenges folder
 */
User: {
  uid: String,
  name: String,
  email: String,
  balance: Integer,
  challenges: [String]
}

/**
 * One folder for challenges, uniquely identified by their uid (generated by
 * Firebase, most likely)
 *
 * participants is a list of Strings, where each string is the email of the user
 *
 * checkInTime is a String in format HH:MM in military time
 * TODO: likely make challenges daily at the same time to keep simple for now
 *
 * checkIns contains checkIn objects where the keys are Strings of dates
 * in the format YYYY-MM-DD.
 */
 Challenge: {
   participants: [String],
   participantNames: [String],
   title: String,
   description: String,
   cost: Integer,
   checkInTime: String,
   checkIns: {
     checkIn1: {
       description: String,
       photoURL: String,
       location: String
     },
     checkIn2: {

     },
     checkIn3: {

     }
   }
 }
